FROM python:3.12-slim

# Installe system dependencies
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    -o Acquire::Retries=3 \
    -o Acquire::http::Timeout=60 \
    -o Acquire::https::Timeout=60 \
    -o Acquire::http::Pipeline-Depth=0 \
    build-essential \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./src ./src
COPY docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir return_files

# Run dev server
CMD ["sh", "-c", "uvicorn src.movie_recommendations:app --host=0.0.0.0 --port=$APP_PORT --reload"]
